import math

DEFAULT_BAUD = 115200
DEFAULT_HZ = 10.0

AUTO_WHEEL_DIAMETER_CM = 6.0
AUTO_WHEEL_RADIUS_CM = AUTO_WHEEL_DIAMETER_CM / 2.0
AUTO_WHEEL_TRACK_CM = 10.0
AUTO_TRUCK_LENGTH_CM = 17.0
AUTO_TRAILER_LENGTH_CM = 22.0
AUTO_START_YAW_RAD = math.pi / 2.0
AUTO_HITCH_HARD_LIMIT_DEG = 45.0
AUTO_HITCH_RELEASE_DEG = 42.0
AUTO_HITCH_RECOVERY_RPM = 25.0
AUTO_MIN_EFFECTIVE_RPM = 60.0

# Hitch real working range (degrees) - used for display during calibration
HITCH_OUT_NEG135 = -103.0
HITCH_OUT_NEG90 = -83.4
HITCH_REAL_ZERO = 0.0
HITCH_REAL_NEG_WORKING = -55.5
HITCH_REAL_POS_WORKING = 55.5

# These are set during runtime calibration (raw ADC values at those positions)
# Default values are placeholders - run calibration to update
HITCH_MEAS_ZERO = 2048.0  # Raw ADC at hitch 0° position
HITCH_MEAS_NEG_WORKING = 1024.0  # Raw ADC at -55.5° position  
HITCH_MEAS_POS_WORKING = 3072.0  # Raw ADC at +55.5° position

MARKER_SIZE_CM = 5.3
WORKSPACE_BOX_SIDE_INSET_CM = 2.0
WORKSPACE_BOX_VERTICAL_EXTEND_CM = 5.0
CAMERA_FOCUS_RELOCK_FRAMES = 30
